name: backport-testing
on:
  push:
    branches:
      - test
jobs:
  backport-tests:
    name: Backport all tests to active releases
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        active-releases: [ 'release/0.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge testing into active release branches
        uses: mtanzi/action-automerge@v1
        id: backport-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'test'
          target: '${{ matrix.active-releases }}'
      - name: Merge testing into active master branch
        uses: mtanzi/action-automerge@v1
        id: backport-master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'test'
          target: 'master'
