name: CI Newsletter
on:
  push:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  ci_newsletter:
    runs-on: ubuntu-latest
    name: CI Newsletter
    if: |
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.body == 'CI Newsletter'
      )
    steps:
      - name: Comment Pull Request CI Newsletter
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "Hello world ${{ github.event_name }}"
          reactions: rocket
          comment-tag: ci_newsletter
          mode: recreate

