name: Comment on PR
on:
  pull_request:
    types: [opened]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: A simple example with a link to a file
    steps:
      - name: Checkout announcement file
        uses: actions/checkout@v4
        with:
          sparse-checkout: ".github/announcements.txt"
          sparse-checkout-cone-mode: false
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: .github/announcements.txt
          message: |
